### ISSUE TITLE
Icons in the KDE Settings dissapear completely with this theme

### ISSUE THREAD

**Issue by marek-lach** [Pr0cella/glassy-kde#1]
... only textual descriptor like 'Global Theme', or 'Display Settings', without any icons visible.

Should be mentioned that this started happening when I switched to the zen kernel I think, although I am not really sure how that's relevant :-)

Other KDE themes work mostly fine...

**Comment by Pr0cella** [comment]
This also happened to me a couple of times. installing another icon pack and reinstalling mine shoulf fix it in most cases. Im not really sure why this happens but I think it has to do with how plasma handles switching which Im not really familiar with.
