### ISSUE TITLE
No blur on titlebars as of Plasma 5.25

### ISSUE THREAD

**Issue by Orangestar12** [Pr0cella/glassy-kde#2]
Window decorations do not have blur as of Plasma 5.25's fix for Korners.

![Screenshot_20221123_085114](https://user-images.githubusercontent.com/785315/203576872-e81e8d3d-169f-4382-8c40-6c665bcdcd25.png)

[The fix requires a Mask element to be added to decoration.svg. I planned to create a patch myself but I can't for the life of me understand the instructions (or the svg format)](https://psifidotos.blogspot.com/2022/03/kornersfix.html)

**Comment by Pr0cella** [comment]
do you use kvantum? you can adjust the transparency in KDE settings  and Kvantum to make them blurry again.

**Comment by Zebouski** [comment]
@Pr0cella How do we do this exactly? I have blur enabled in Desktop Effects, but I see no option in kvantum to fix titlebars.

Would love to see this theme restored to its former glory!

**Comment by rplazevedo** [comment]
@Zebouski @Orangestar12 I managed to fix this. Just unpack this and drop the two folders into  /-.local/share/aurorae/themes/.
I can fork the repo and add it as a new theme if you want.

[Glassy.tar.gz](https://github.com/user-attachments/files/15917770/Glassy.tar.gz)

**Comment by Zebouski** [comment]
Thank you man, great job I really appreciate! My desktop is beautiful once again.

**Comment by rplazevedo** [comment]
There is still some slight discrepancy in the tint between the title bar and the window itself, but I couldn't figure out what it was. Only happens for the normal version. I made a pull request to fix the blur issue though.
