### ISSUE TITLE
Controlbar can't be reduced below 48px since Plasma 5.27.3

### ISSUE THREAD

**Issue by Nudnik-de** [Pr0cella/glassy-kde#3]
Glassy KDE is my favorite plasma theme. Did the update to plasma 5.27.3, coming from 5.26.5 and now the controlbar height is enlarged to 48 px. Can't reduce further, only increase. Crosschecked with other themes, seams only Glassy is effected.

![Screenshot_20230401_144656](https://user-images.githubusercontent.com/95722484/229289733-f43ce7b4-1355-4d2a-9420-2e8a60adb601.png)

**Comment by Pr0cella** [comment]
cannot reproduce this unfortunately. although the control bar has been acting act up lately for me too. I would suggest just using latte dock. the plasma task bar can be difficult to configure without major bugs. i dont really know why though.

**Comment by Terria-K** [comment]
This is also an issue on the latest plasma version as well

<img width="766" height="555" alt="Image" src="https://github.com/user-attachments/assets/b2533df7-0a3b-44aa-a54e-1dcc8e8473e6" />
